
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcvgzmuymzvlbcbagcoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjdmd6bXV5bXp2bGJjYmFnY29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyODc3MjUsImV4cCI6MjA0OTg2MzcyNX0.fKEF2RVjPQiYxTzbyXxEYFV80ipEZRJ_XTN9KsW46LE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
